### ISSUE TITLE
Take ownership of the repository

### ISSUE THREAD

**Issue by zonca** [zonca/python-qucs#2]
@0xDBFB7 I'm not using nor maintaining this package anymore,
would you like to take ownership of the repository?
If so I can proceed to transfer under your account.

**Comment by 0xDBFB7** [comment]
You refer to having developed this package in your paper, would it cause issues if the author changes? 

You could just archive this repo and put a link to 0xDBFB7/python-qucs in the README, but I'm not sure I'll be developing my fork either - sorry for all the trouble.

**Comment by zonca** [comment]
That would not be a problem,
Anyway if you are not sure yet,
Let's keep as it is, please contribute back any change.
if in the future you can commit to maintaining the repository we can proceed to the transfer later on.
