### ISSUE TITLE
Demo run - reported errors

### ISSUE THREAD

**Issue by Circa-Tree** [zonca/python-qucs#3]
I ran the demo using ERIC6 Python, and got the following errors reported in ERIC6 ;

> checking netlist...
checker notice, value of `Temp' (variable `Tsky_C') could be out of range `[-273.15,0.' in `Pac:SkyLoad'
checker notice, variable `acfrequency' in equation `Freq_GHz' not yet defined
checker notice, variable `S' in equation `s21db' not yet defined
checker notice, variable `out.vn' in equation `outvolts_log' not yet defined
checker notice, variable `out.vn' in equation `outvolts_tot_V' not yet defined

> checking netlist...
checker notice, value of `Temp' (variable `Tsky_C') could be out of range `[-273.15,0.' in `Pac:SkyLoad'
checker notice, variable `acfrequency' in equation `Freq_GHz' not yet defined
checker notice, variable `S' in equation `s21db' not yet defined
checker notice, variable `out.vn' in equation `outvolts_log' not yet defined
checker notice, variable `out.vn' in equation `outvolts_tot_V' not yet defined

> creating netlist...
checker notice, variable `acfrequency' in equation `Freq_GHz' not yet defined
checker notice, variable `S' in equation `s21db' not yet defined
checker notice, variable `out.vn' in equation `outvolts_log' not yet defined
checker notice, variable `out.vn' in equation `outvolts_tot_V' not yet defined
checker notice, variable `acfrequency' in equation `Freq_GHz' not yet defined
checker notice, variable `S' in equation `s21db' not yet defined
checker notice, variable `out.vn' in equation `outvolts_log' not yet defined
checker notice, variable `out.vn' in equation `outvolts_tot_V' not yet defined
checker notice, netlist OK

> WARNING: Operating frequency (3.5e+10) beyond cutoff frequency (3.27584e+10).
... (all frequencies)
WARNING: Operating frequency (4.99e+10) beyond cutoff frequency (3.27584e+10).
WARNING: Operating frequency (5e+10) beyond cutoff frequency (3.27584e+10).

> WARNING: Operating frequency (3.5e+10) beyond cutoff frequency (3.27584e+10).
... (all frequencies)
WARNING: Operating frequency (4.99e+10) beyond cutoff frequency (3.27584e+10).
WARNING: Operating frequency (5e+10) beyond cutoff frequency (3.27584e+10).

> checking netlist...
checker notice, value of `Temp' (variable `Tsky_C') could be out of range `[-273.15,0.' in `Pac:SkyLoad'
checker notice, variable `acfrequency' in equation `Freq_GHz' not yet defined
checker notice, variable `S' in equation `s21db' not yet defined
checker notice, variable `out.vn' in equation `outvolts_log' not yet defined
checker notice, variable `out.vn' in equation `outvolts_tot_V' not yet defined

QUCS showed the two plots verses frequency, and a popup window of the slider controls appeared, and a popup window with the adjustable graph with gridlines appeared (but had no graph lines plotted on it).

I am not sure if the program worked eventually and th errors were just at the beginning stage of analysis, or if the errors are the reason why there were no graphlines plotted on the popup graph.

Q1) Are these real errors?

Q2) Should the popup graph show any graphlines? and how to get the graphlines to show?

**Comment by zonca** [comment]
sorry, not maintaining this package anymore.
